services:
- docker
env:
- dist='ubuntu.yakkety'
- dist='ubuntu.xenial'
- dist='debian.stretch'
- dist='debian.sid'
- dist='raspbian.jessie'
- dist='raspbian.sid'
script:
- if [[ $TRAVIS_COMMIT_MESSAGE == *"updated package metadata"* ]] || [[ $TRAVIS_COMMIT_MESSAGE
  == *"rebuild-release"* ]]; then cd build_support && make dist=$dist;
  else echo "Not building artifacts, since this is not a version change commit"; fi;
branches:
  only:
  - master
before_deploy:
- export VERSION_TAG=v$(cat $TRAVIS_BUILD_DIR/VERSION)
- rm -r $TRAVIS_BUILD_DIR/dist/*/ && rm -f $TRAVIS_BUILD_DIR/dist/*.build
- cd $TRAVIS_BUILD_DIR/dist && sha256sum *${dist}* > ${VERSION_TAG}.${dist}.sha256.txt
  && tar -zcvf ${VERSION_TAG}.${dist}.assets.tar.gz *${dist}* && echo "" >> ${VERSION_TAG}.${dist}.sha256.txt
  && sha256sum ${VERSION_TAG}.${dist}.assets.tar.gz >> ${VERSION_TAG}.${dist}.sha256.txt
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis"
- git tag $VERSION_TAG --force -a -m "Travis build $TRAVIS_BUILD_NUMBER"
- sleep 15
deploy:
  on:
    condition: $TRAVIS_COMMIT_MESSAGE =~ "updated package metadata" || $TRAVIS_COMMIT_MESSAGE
      =~ "rebuild-release"
    repo: open-horizon/horizon-deb-packager
  provider: releases
  skip_cleanup: true
  api_key:
    secure: kmSjhGttxX9GacriqEpBKS8L3A7C42juRlKdAhbJOOo6Er856iMMUq5qLgo0Mr5/7hA4o8PMI3rDSAxjPcYATHvlCh02o0NwqCwLAgD9uzgHEylH1F3u6mkKNUFUHK+zVQ0ePKQeqkm9w7jWLLH5K/EWWqok/T49dnCF8ejk02ksQLAN6uL9YLySuDrNhWY/JjJ4vjIJq2B7zAdRqU5FK+nAr6pYtJSanmBuqFP2DkWamy21lWOqFTis06rPwYBiulMcFOTPd8m/IUrc38BWudv/KV+OcRhoySfAihFX3LRnAAkwS7AKEMM2uckqimKgrkPZ7M7tMiSExPLzb0DJ1/TVnpwg6zLGkpe2ZzGJqY06Bp1Cz2R/pAhHx+uIDav6eRCw0l4SQDU1aDYSPzHjBVI3WqePnx2bHoYAeNlngLiVZQntrWTU9y1R+Aqa175jdRgNH3dxKChLof8bDHGYP6CctdkSav2K27llcLVl+q18QVydUCl07vxJmesPgD15oeYRiq59fyXMH5aJzLD718AjY9nF5aHxO/2DljxD36nMWMyZX2Q8eiqWmeX9fl8V9veNk6+FUsWJS+gcPY+VoEr1Zs7PXM8vcL/a8y/0VKw+yhz5yU4ALai1j/xBYyUTNh8t9etrXEMgylY6IQCFIw5kqwdH5DWQbnmkcHeKKXY=
  file:
  - "$TRAVIS_BUILD_DIR/dist/${VERSION_TAG}.${dist}.assets.tar.gz"
  - "$TRAVIS_BUILD_DIR/dist/${VERSION_TAG}.${dist}.sha256.txt"
  draft: false
  overwrite: true
notifications:
  slack:
    secure: AfNiLrG7WJi304rjSIl6V0pMQgydY//Mo7okJP50WqkqxRLu3sZ30i5whjDHycCgbE+CjAhkgHXJX4ZVliZwpOtv/bfM7AjjlKiJiW+BE2dehoW62K441dDWao1hyoiTFpjt+QnPUFgx8PqDrfcbyoluJMfHLKQ/fkiKccWiux3yFSFFoWgfnRJDi+tdBsBiH9thgFjqru9a1yPymyMsVJul/MSE2Bp0t0fnDWM/VNnfr+5Ok8EN84Fr11MuavV5F5YYXRePthVm+TYLxFrkoJmV2PRgkwbzR9X/AdSLoOHR4AXJJmMXTxMzlHnWaHL/GqzEEnWYCYOjJ+FxM2PNFpcJqfka4bPPDKT/guRtjfqX2GoU/NQNJVZmbO/lxl4MiL5mSa5+lGhOyPn/AUWo15afzWHvJ9yBN5t4RQ65sNidpGtop3lMj/cx2QN3nmdvf3cGMSRbSrdNN2JNEjf1t2PyhziHhC0ntGuQSyF29RKLOO7FNbA3HKbCJOjvnhQeHSsRKc3VZw8NYW8CqyaLYvnL96mihz7fwj5XVgx8Y4ErdIRGXexiZP1ox2EeBmTaiCXgrivuubru7rMXtHrqCYKaXj455WtY9FCFp7o99xEQF1GC2Wr8fRjvAGUXDHJ9rLOgt9rN3ek0rv/Qg7WcVe1UZp6AedxW4S5bTDSgmZ8=
