services:
- docker
env:
- dist='ubuntu.yakkety'
- dist='ubuntu.xenial'
- dist='raspbian.jessie'
- dist='raspbian.sid'
- dist='debian.sid'
script:
- if [[ $TRAVIS_COMMIT_MESSAGE == *"updated package metadata"* ]] 
  || [[ $TRAVIS_COMMIT_MESSAGE == *"rebuild-release"* ]]; then cd build_support && make arch=armhf dist=$dist;
  else echo "Not building artifacts, since this is not a version change commit"; fi;
branches:
  only:
  - master
before_deploy:
- export VERSION_TAG=v$(cat $TRAVIS_BUILD_DIR/VERSION)
- rm -r $TRAVIS_BUILD_DIR/dist/*/ && rm -f $TRAVIS_BUILD_DIR/dist/*.build
- cd $TRAVIS_BUILD_DIR/dist && sha256sum *${dist}* > ${VERSION_TAG}.${dist}.sha256.txt
  && tar -zcvf ${VERSION_TAG}.${dist}.assets.tar.gz *${dist}* && echo "" >> ${VERSION_TAG}.${dist}.sha256.txt
  && sha256sum ${VERSION_TAG}.${dist}.assets.tar.gz >> ${VERSION_TAG}.${dist}.sha256.txt
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis"
- if git tag $VERSION_TAG -a -m "Travis build $TRAVIS_BUILD_NUMBER" 2>/dev/null; then
  echo "Creating tag $VERSION_TAG"; else echo "Tag already exists"; fi;
- sleep 15
deploy:
  on:
    condition: $TRAVIS_COMMIT_MESSAGE =~ "updated package metadata" || $TRAVIS_COMMIT_MESSAGE =~ "rebuild-release"
    repo: open-horizon/horizon-deb-packager
  provider: releases
  skip_cleanup: true
  api_key:
    secure: kmSjhGttxX9GacriqEpBKS8L3A7C42juRlKdAhbJOOo6Er856iMMUq5qLgo0Mr5/7hA4o8PMI3rDSAxjPcYATHvlCh02o0NwqCwLAgD9uzgHEylH1F3u6mkKNUFUHK+zVQ0ePKQeqkm9w7jWLLH5K/EWWqok/T49dnCF8ejk02ksQLAN6uL9YLySuDrNhWY/JjJ4vjIJq2B7zAdRqU5FK+nAr6pYtJSanmBuqFP2DkWamy21lWOqFTis06rPwYBiulMcFOTPd8m/IUrc38BWudv/KV+OcRhoySfAihFX3LRnAAkwS7AKEMM2uckqimKgrkPZ7M7tMiSExPLzb0DJ1/TVnpwg6zLGkpe2ZzGJqY06Bp1Cz2R/pAhHx+uIDav6eRCw0l4SQDU1aDYSPzHjBVI3WqePnx2bHoYAeNlngLiVZQntrWTU9y1R+Aqa175jdRgNH3dxKChLof8bDHGYP6CctdkSav2K27llcLVl+q18QVydUCl07vxJmesPgD15oeYRiq59fyXMH5aJzLD718AjY9nF5aHxO/2DljxD36nMWMyZX2Q8eiqWmeX9fl8V9veNk6+FUsWJS+gcPY+VoEr1Zs7PXM8vcL/a8y/0VKw+yhz5yU4ALai1j/xBYyUTNh8t9etrXEMgylY6IQCFIw5kqwdH5DWQbnmkcHeKKXY=
  file:
  - "$TRAVIS_BUILD_DIR/dist/${VERSION_TAG}.${dist}.assets.tar.gz"
  - "$TRAVIS_BUILD_DIR/dist/${VERSION_TAG}.${dist}.sha256.txt"
  draft: false
  overwrite: true
notifications:
  slack:
    secure: Mcl4sVGPyLBmHh8PQYduI6kQD3z+Mx/doMS/y6QCLCI+skN6DJePCWP9jgANH8weiAPtE5nNo5D++QAF8yfGwIFnXcoNJbk2VNMOOJP4gCkGMlxiVN+/pkY51lB6pgptsTuz3ATgwLD+rxGG6ihTf8I9hzR7yq98iH+sudL8HN5VqklkINeJspOmq7KdiCY+xBUNu4VFt36gI1tfsopDaNd+mEqRznUW3SBnVlaCWczV7oxD2bWOUOPW2wdNitY8jE753OCnwJa0vXaQdpgGWJ1N8dMF3sWMIpj/U18PK37eJMwESmfQo1d7c4dYd/jczesS+ZoXgay+P9OR6xrZdfqxJ6wwzLHjZF6ZmqxFjm6aUXgrZj/Y9KXaMoX/qM0pgcADT48jDyLciwBmnsa7li+ZEUgVOT9OKByiGHn5KuJ/xCLW9lbNYbsBw08a36YneyUqASCZDwjVGU+KVwrSNdPXRJsjxdkDVngAlSaNvUwyE1S5i1AWIlGgzDQRuPKsmXihNco5JrX8w+vL5n+N3aCWI9AX8jkeNSfXeZIqCS/rEFKV84uLWi4QhmTu1MJWrAFk88Gax/NY7PPCnI/oAFZ7yC2BV3tOjOTOIGNJQzRNhYK/Qp/o8R5seia7Mpv1ilLmDKEFAg3SLY7dPpC/sEQM8Wc1iWu0KsqJaKKPXHQ=
